# https://just-the-docs.github.io/just-the-docs/docs/configuration/
remote_theme: just-the-docs/just-the-docs
color_scheme: light

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
